services:
  - type: web
    name: 3d-eus-ai
    runtime: python
    runtimeVersion: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
